# Generated by Selenium IDE
import pytest
import time
from time import sleep
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchpython():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    options.add_argument("--no-sandbox")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchpython(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.set_window_size(1026, 686)
    self.driver.find_element(By.ID, "kw").send_keys("Python")
    self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
    sleep(3)
    assert self.driver.find_element(By.XPATH, "//div[@id=\'1\']/h3/a/em").text == "Python"
    
